name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.9.10" # install the python version needed

      - name: Install pip dependencies
        run: |

          pip install --upgrade pip
          pip install wheel setuptools pip --upgrade
          # pip install pip==21.3.1
          pip install -r requirements.txt
      - name: Run Test
        env:
          USER_NAME: ${{secrets.USER_NAME}}
          ACCESSKEY: ${{secrets.ACCESSKEY}}
        run: export BROWSERSTACK_CONFIG_FILE="Robot/Resources/config/android/browserstack-local.yml" && browserstack-sdk robot Robot/Tests/android.robot
